### ISSUE TITLE
Unable to access Redis Master via Sentinel using different Clients [Help wanted]

### ISSUE THREAD

**Issue by sandeep-yeleswarapu** [spotahome/redis-operator#255]
### Expected behaviour

Be able to ping the Redis Master and set a key/value pair.

### Actual behaviour

Timeout error, when trying to connect to the master via Sentinnel. The sentinel is able to identify the master though.
Could be because of the private ip address of the Kubernetes cluster.

### Steps to reproduce the behaviour

Issue occurs with both Python (redis-py) and Java (jedis) clients.
Deployed redisfailover on Kubernetes cluster using helm charts using the default configuration.

**_redis-py:_**
    >>> from redis.sentinel import Sentinel
    >>> sentinel = Sentinel([('localhost', 26379)], socket_timeout=0.1)
    >>> master = sentinel.master_for('mymaster', socket_timeout=0.1)
    >>> master.set('foo', 'bar')  => ##Timeout here

**_jedis:_**
jedisSentinelPool = new JedisSentinelPool("mymaster", sentinels);
jedisSentinelPool.getResource() => ##Timeout here

### Environment

How are the pieces configured?
* Redis Operator version - Latest
* Kubernetes version - 1.15

### Logs

_**redis-py:**_

  File "/Library/Python/2.7/site-packages/redis/sentinel.py", line 44, in connect
    self.connect_to(self.connection_pool.get_master_address())
  File "/Library/Python/2.7/site-packages/redis/sentinel.py", line 34, in connect_to
    super(SentinelManagedConnection, self).connect()
  File "/Library/Python/2.7/site-packages/redis/connection.py", line 554, in connect
    raise TimeoutError("Timeout connecting to server")
redis.exceptions.TimeoutError: Timeout connecting to server

**_jedis:_**

Could not get a resource from the pool
redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.jedis.util.Pool.getResource(Pool.java:59)
	at redis.clients.jedis.JedisSentinelPool.getResource(JedisSentinelPool.java:235)
	at com.lexisnexis.datastore.CacheSentinelTest.setup(CacheSentinelTest.java:30)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Failed connecting to host 10.1.1.134:6379
	at redis.clients.jedis.Connection.connect(Connection.java:204)
	at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:100)
	at redis.clients.jedis.BinaryJedis.connect(BinaryJedis.java:1894)
	at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:117)
	... 60 more
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at redis.clients.jedis.Connection.connect(Connection.java:181)

**Comment by spsy** [comment]
In case if this is not possible, is there a role based labelling that we can rely on to identify the master server, without the sentinels?

**Comment by ThomasK33** [comment]
Have you considered increasing the socket_timeout?

**Comment by sandeep-yeleswarapu** [comment]
Yes, we did increase the socket_timeout and that had no effect.
